import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  keyboardArea: {
    flex: 1,
  },
  landing: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  landingLogo: {
    alignSelf: 'center',
    color: '#03BDE7',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 27,
    marginTop: 48,
  },
  landingImage: {
    ...StyleSheet.absoluteFillObject,
    height: '90%',
    width: '100%',
    overflow: 'hidden',
  },
  emergencyPanel: {
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    bottom: 0,
    left: 0,
    paddingBottom: 32,
    paddingHorizontal: 16,
    paddingTop: 30,
    position: 'absolute',
    right: 0,
  },
  emergencyRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 26,
  },
  emergencyItem: {
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  emergencyDivider: {
    backgroundColor: 'rgba(255,255,255,0.38)',
    height: 34,
    width: 1,
  },
  emergencyLabel: {
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 10,
  },
  whiteButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    justifyContent: 'center',
    minHeight: 54,
  },
  whiteButtonText: {
    color: '#03BDE7',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
  },
  formContent: {
    flexGrow: 1,
    paddingBottom: 34,
    paddingHorizontal: 18,
    paddingTop: 28,
  },
  passwordContent: {
    flexGrow: 1,
    paddingBottom: 34,
    paddingHorizontal: 19,
    paddingTop: 30,
  },
  signupContent: {
    flexGrow: 1,
    paddingBottom: 34,
    paddingHorizontal: 16,
    paddingTop: 18,
  },
  topLabel: {
    alignSelf: 'center',
    color: '#00AEEA',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    marginBottom: 24,
  },
  topLabelGradient: {
    alignSelf: 'center',
    height: 20,
    marginBottom: 24,
    width: 120,
  },
  bigTitle: {
    color: '#08B9D8',
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 34,
    lineHeight: 35,
    marginBottom: 14,
  },
  bigTitleGradient: {
    height: 76,
    marginBottom: 14,
    width: 300,
  },
  bodyText: {
    color: '#8C8C8C',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
  },
  authInput: {
    borderColor: '#B7B7B7',
    borderRadius: 12,
    borderWidth: 1,
    color: '#333333',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    height: 44,
    paddingHorizontal: 12,
  },
  paperInput: {
    backgroundColor: '#FFFFFF',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    height: 50,
    marginBottom: 14,
  },
  gradientButton: {
    borderRadius: 10,
    marginTop: 14,
    overflow: 'hidden',
  },
  gradientButtonFill: {
    alignItems: 'center',
    height: 51,
    justifyContent: 'center',
  },
  gradientButtonText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 13,
  },
  emailSpacer: {
    flex: 1,
    minHeight: 220,
  },
  orText: {
    alignSelf: 'center',
    color: '#989898',
    fontFamily: 'Poppins-Regular',
    fontSize: 13,
    marginBottom: 12,
  },
  googleButton: {
    alignItems: 'center',
    borderColor: '#D0D0D0',
    borderRadius: 9,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 22,
    height: 46,
    justifyContent: 'center',
  },
  googleIcon: {
    color: '#4285F4',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 19,
  },
  googleText: {
    color: '#777777',
    fontFamily: 'Poppins-Medium',
    fontSize: 14,
  },
  termsText: {
    alignSelf: 'center',
    color: '#777777',
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 44,
    textAlign: 'center',
  },
  linkText: {
    color: '#00AEEA',
    fontFamily: 'Poppins-Medium',
  },
  backHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    minHeight: 34,
    marginBottom: 34,
  },
  backButton: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  backLabel: {
    color: '#00AEEA',
    flex: 1,
    fontFamily: 'Poppins-SemiBold',
    fontSize: 14,
    marginRight: 32,
    textAlign: 'center',
  },
  backLabelGradient: {
    alignItems: 'center',
    flex: 1,
    marginRight: 32,
  },
  passwordField: {
    borderColor: '#03CDF4',
    borderRadius: 14,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    marginTop: 4,
    paddingHorizontal: 16,
  },
  floatingField: {
    borderColor: '#C9C9C9',
    borderRadius: 12,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    marginBottom: 17,
    paddingHorizontal: 12,
  },
  floatingLabel: {
    backgroundColor: '#FFFFFF',
    color: '#B0B0B0',
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    left: 10,
    paddingHorizontal: 2,
    position: 'absolute',
    top: -9,
  },
  floatingInput: {
    color: '#333333',
    flex: 1,
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    paddingRight: 34,
  },
  fieldIcon: {
    position: 'absolute',
    right: 13,
  },
  clearField: {
    position: 'absolute',
    right: 13,
  },
  resetButton: {
    alignSelf: 'flex-start',
    marginTop: 24,
  },
  resetText: {
    color: '#333333',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
  },
  avatarPicker: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#A0A0A0',
    borderRadius: 55,
    borderWidth: 1,
    height: 110,
    justifyContent: 'center',
    marginBottom: 34,
    width: 110,
    overflow: 'hidden',
  },
  avatarImage: {
    height: '100%',
    width: '100%',
  },
  avatarPlus: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#9A9A9A',
    borderRadius: 10,
    borderWidth: 1,
    bottom: 5,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: 4,
    width: 18,
  },
  avatarPlusText: {
    color: '#333333',
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    lineHeight: 16,
  },
  termsRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    marginHorizontal: 4,
    marginTop: 6,
  },
  checkbox: {
    alignItems: 'center',
    backgroundColor: '#E2E2E2',
    borderRadius: 3,
    height: 12,
    justifyContent: 'center',
    marginTop: 3,
    width: 12,
  },
  checkboxActive: {
    backgroundColor: '#03BDE7',
  },
  termsRowText: {
    color: '#777777',
    flex: 1,
    fontFamily: 'Poppins-Regular',
    fontSize: 11,
    lineHeight: 18,
  },
  signupButtonWrap: {
    marginTop: 64,
  },
  errorText: {
    color: '#B42318',
    fontFamily: 'Poppins-SemiBold',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 10,
  },
  pressed: {
    opacity: 0.72,
  },
});

export { styles };
