import { StyleSheet } from 'react-native';

const WORKSPACES_FONTS = {
  regular: "Poppins-Regular",
  medium: "Poppins-Medium",
  semiBold: "Poppins-SemiBold",
  bold: "Poppins-Bold",
  extraBold: "Poppins-ExtraBold",
} as const;

const WORKSPACE_GRADIENT_COLORS = ['#03CDF4', '#019BDE', '#01EBD0'] as const;
const WORKSPACE_GRADIENT_LOCATIONS = [0.08, 0.48, 1] as const;

const styles = StyleSheet.create({
  formScreen: { flex: 1, backgroundColor: '#F6FAFE' },
  formTitle: { flex: 1, textAlign: 'center', color: '#101828', fontFamily: WORKSPACES_FONTS.semiBold, fontSize: 21, lineHeight: 30 },
  headerBalance: { width: 44 },
  formDescription: { color: '#667085', fontFamily: WORKSPACES_FONTS.regular, fontSize: 13, lineHeight: 21, textAlign: 'center', marginTop: 8, marginBottom: 24, paddingHorizontal: 12 },
  formBody: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E7EEF5', borderRadius: 22, padding: 20 },
  formFooter: { backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#E7EEF5', paddingHorizontal: 22, paddingTop: 16, paddingBottom: 4 },
  footerContent: { width: '100%', maxWidth: 520, alignSelf: 'center' },
  cancelButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center' },
  cancelButtonText: { color: '#667085', fontFamily: WORKSPACES_FONTS.medium, fontSize: 13 },
  photoSection: { marginBottom: 22 },
  photoPreview: { width: '100%', minHeight: 158, aspectRatio: 1.9, borderRadius: 14, borderWidth: 1, borderColor: '#D8E7EF', backgroundColor: '#F6FAFE', overflow: 'hidden' },
  photoPlaceholder: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
  photoIcon: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#E4F5FC', alignItems: 'center', justifyContent: 'center' },
  photoTitle: { color: '#019BDE', fontFamily: WORKSPACES_FONTS.semiBold, fontSize: 14, marginTop: 10 },
  photoActions: { flexDirection: 'row', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  photoAction: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 4 },
  photoActionText: { color: '#019BDE', fontFamily: WORKSPACES_FONTS.medium, fontSize: 12 },
  photoRemoveText: { color: '#B42318', fontFamily: WORKSPACES_FONTS.medium, fontSize: 12 },
  photoLoading: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(255,255,255,0.7)', alignItems: 'center', justifyContent: 'center' },
  flex: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    paddingHorizontal: 26,
    paddingTop: 28,
    paddingBottom: 144,
    backgroundColor: '#FFFFFF',
  },
  formScreenContent: {
    width: '100%',
    maxWidth: 564,
    alignSelf: 'center',
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 24,
  },
  title: {
    flexShrink: 1,
    height: 42,
    width: 136,
  },
  hero: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 18,
    marginBottom: 20,
  },
  titleSvg: {
    height: 38,
    width: 190,
  },
  titleSmall: {
    color: "#101828",
    fontFamily: WORKSPACES_FONTS.extraBold,
    fontSize: 25,
    lineHeight: 31,
  },
  subtitle: {
    color: "#4B5563",
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 16,
    lineHeight: 21,
    marginTop: 0,
  },
  addButton: {
    alignItems: "center",
    height: 44,
    justifyContent: "center",
    marginTop: 2,
    width: 44,
  },
  heroActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  inviteButton: {
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    borderColor: '#B9E6FE',
    borderRadius: 12,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  pressed: {
    opacity: 0.72,
  },
  centerState: {
    alignItems: "center",
    paddingTop: 42,
    gap: 10,
  },
  centerStateText: {
    color: "#667085",
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 14,
  },
  errorText: {
    color: "#B42318",
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 14,
  },
  emptyCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#E7EEF5",
    borderRadius: 20,
    borderWidth: 1,
    padding: 22,
  },
  emptyTitle: {
    color: "#101828",
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 17,
    marginTop: 10,
  },
  emptyText: {
    color: "#667085",
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    textAlign: "center",
  },
  workspaceCardGradient: {
    borderRadius: 13,
    marginBottom: 24,
    padding: 1,
  },
  workspaceCard: {
    marginBottom: 24,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    minHeight: 124,
    overflow: "hidden",
    borderColor: "#B3B3B3",
    borderWidth: 1,
  },
  workspaceImageWrap: {
    height: 182,
    position: "relative",
    width: "100%",
  },
  workspaceImage: {
    height: "100%",
    width: "100%",
  },
  workspaceImagePlaceholder: {
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    gap: 8,
    height: "100%",
    justifyContent: "center",
    width: "100%",
  },
  workspaceImagePlaceholderText: {
    color: "#64748B",
    fontFamily: WORKSPACES_FONTS.medium,
    fontSize: 13,
  },
  workspaceMenuButton: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.96)",
    borderRadius: 999,
    elevation: 3,
    height: 36,
    justifyContent: "center",
    position: "absolute",
    right: 12,
    shadowColor: "#101828",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 6,
    top: 12,
    width: 36,
  },
  workspaceActionsOverlay: {
    backgroundColor: "rgba(17, 24, 39, 0.46)",
    flex: 1,
    justifyContent: "flex-end",
  },
  workspaceActionsCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  workspaceActionsTitle: {
    color: "#101828",
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 22,
  },
  workspaceActionsSubtitle: {
    color: "#667085",
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 14,
    marginBottom: 20,
    marginTop: 3,
  },
  workspaceActionRow: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: "#E7EEF5",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    minHeight: 72,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  workspaceActionDangerRow: {
    backgroundColor: "#FFFBFA",
    borderColor: "#FEE4E2",
    marginTop: 10,
  },
  workspaceActionIcon: {
    alignItems: "center",
    backgroundColor: "#EAF3FB",
    borderRadius: 12,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  workspaceActionDangerIcon: {
    backgroundColor: "#FEE4E2",
  },
  workspaceActionCopy: {
    flex: 1,
    marginLeft: 12,
  },
  workspaceActionTitle: {
    color: "#101828",
    fontFamily: WORKSPACES_FONTS.semiBold,
    fontSize: 15,
  },
  workspaceActionDangerTitle: {
    color: "#B42318",
  },
  workspaceActionDescription: {
    color: "#667085",
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  workspaceActionsCancel: {
    alignItems: "center",
    marginTop: 10,
    paddingVertical: 13,
  },
  workspaceActionsCancelText: {
    color: "#475467",
    fontFamily: WORKSPACES_FONTS.semiBold,
    fontSize: 14,
  },
  inviteCodeInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D0DDE6',
    borderRadius: 12,
    borderWidth: 1,
    color: '#101828',
    fontFamily: WORKSPACES_FONTS.medium,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 14,
  },
  acceptInviteButton: {
    alignItems: 'center',
    backgroundColor: '#019BDE',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 14,
    minHeight: 50,
  },
  acceptInviteButtonDisabled: {
    opacity: 0.68,
  },
  acceptInviteButtonText: {
    color: '#FFFFFF',
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 15,
  },
  deleteSheetOverlay: {
    backgroundColor: "rgba(17, 24, 39, 0.42)",
    flex: 1,
    justifyContent: "flex-end",
  },
  deleteSheetCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 26,
  },
  deleteSheetTitle: {
    color: "#101828",
    fontFamily: WORKSPACES_FONTS.extraBold,
    fontSize: 22,
    textAlign: "center",
  },
  deleteSheetWarningIcon: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: "#FEE4E2",
    borderRadius: 999,
    height: 52,
    justifyContent: "center",
    marginBottom: 12,
    width: 52,
  },
  deleteSheetDescription: {
    color: "#475467",
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 15,
    lineHeight: 21,
    marginTop: 8,
    textAlign: "center",
  },
  deleteSheetConfirmButton: {
    alignItems: "center",
    backgroundColor: "#B42318",
    borderRadius: 12,
    marginTop: 20,
    minHeight: 46,
    justifyContent: "center",
  },
  deleteSheetConfirmText: {
    color: "#FFFFFF",
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 14,
  },
  deleteSheetCancelButton: {
    alignItems: "center",
    marginTop: 14,
    minHeight: 36,
    justifyContent: "center",
  },
  deleteSheetCancelText: {
    color: "#98A2B3",
    fontFamily: WORKSPACES_FONTS.medium,
    fontSize: 14,
  },
  workspaceCardFooter: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 60,
    paddingHorizontal: 22,
  },
  workspaceName: {
    color: "#101828",
    flex: 1,
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 20,
    lineHeight: 26,
    paddingRight: 14,
  },
  formHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  backButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E7EEF5',
    backgroundColor: '#FFFFFF',
  },
  formHeaderText: {
    flex: 1,
  },
  avatarWrap: {
    alignSelf: 'center',
    marginBottom: 24,
    marginTop: 12,
    position: 'relative',
    alignItems: 'center',
  },
  avatarCircle: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#A7B0BA',
    borderRadius: 999,
    borderWidth: 1,
    height: 132,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 132,
  },
  avatarImage: {
    height: '100%',
    width: '100%',
  },
  avatarPlusBubble: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#A7B0BA',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    position: 'absolute',
    right: -2,
    bottom: 4,
    width: 30,
  },
  avatarPlusBubbleText: {
    color: '#101828',
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 18,
    lineHeight: 20,
  },
  avatarHintText: {
    color: '#667085',
    fontFamily: WORKSPACES_FONTS.medium,
    fontSize: 12,
    marginTop: 8,
  },
  formCard: {
    gap: 8,
  },
  inputLabel: {
    color: '#344054',
    fontFamily: WORKSPACES_FONTS.semiBold,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D0DDE6',
    borderRadius: 12,
    borderWidth: 1,
    color: '#101828',
    fontFamily: WORKSPACES_FONTS.regular,
    fontSize: 15,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  slugPreview: {
    backgroundColor: "#F0F9FF",
    borderRadius: 14,
    padding: 12,
  },
  slugLabel: {
    color: "#667085",
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 12,
  },
  slugValue: {
    color: "#019BDE",
    fontFamily: WORKSPACES_FONTS.bold,
    fontSize: 14,
    marginTop: 4,
  },
  primaryButton: {
    borderRadius: 16,
    minHeight: 54,
    overflow: "hidden",
  },
  primaryButtonGradient: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    minHeight: 54,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontFamily: WORKSPACES_FONTS.extraBold,
    fontSize: 16,
  },
});

export {
  WORKSPACE_GRADIENT_COLORS,
  WORKSPACE_GRADIENT_LOCATIONS,
  WORKSPACES_FONTS,
  styles,
};
