import { StyleSheet } from 'react-native';

const WORKSPACE_DETAILS_FONTS = {
  regular: 'Poppins-Regular',
  medium: 'Poppins-Medium',
  semiBold: 'Poppins-SemiBold',
  bold: 'Poppins-Bold',
} as const;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 144,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },
  backButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 12,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    marginRight: 8,
    width: 36,
  },
  headerTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 22,
    lineHeight: 28,
  },
  workspaceMetrics: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  metricPill: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  metricText: {
    color: '#344054',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 12,
  },
  subtitle: {
    color: '#777777',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    marginBottom: 15,
    marginTop: 2,
  },
  alertToggleRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  alertToggleTextWrap: {
    flex: 1,
    marginRight: 12,
  },
  alertToggleTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 13,
  },
  alertToggleSubtitle: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 4,
  },
  sectionTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 17,
  },
  sectionSubtitle: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 2,
    maxWidth: 250,
  },
  live: {
    color: '#00A8CC',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
  },
  sectionActionButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#D8E7EF',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  sectionActionText: {
    color: '#00326D',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 12,
  },
  activityCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    flexDirection: 'row',
    marginBottom: 10,
    padding: 15,
  },
  snapshotCard: {
    marginBottom: 20,
  },
  snapshotHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 10,
  },
  roomsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  cameraList: {
    gap: 10,
    marginBottom: 24,
    marginTop: 4,
  },
  cameraRow: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 104,
    padding: 12,
  },
  cameraRowMain: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    minHeight: 48,
    minWidth: 0,
  },
  cameraIconBox: {
    alignItems: 'center',
    backgroundColor: '#F0F6FC',
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  cameraInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  cameraName: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 14,
    lineHeight: 20,
  },
  cameraMeta: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 1,
  },
  cameraStatusDot: {
    backgroundColor: '#98A2B3',
    borderRadius: 999,
    height: 8,
    marginLeft: 8,
    width: 8,
  },
  cameraStatusDotOnline: {
    backgroundColor: '#12B76A',
  },
  iconActionButton: {
    alignItems: 'center',
    borderRadius: 12,
    height: 42,
    justifyContent: 'center',
    marginLeft: 4,
    width: 42,
  },
  cameraRowActions: {
    borderTopColor: '#EEF2F6',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
    paddingTop: 9,
  },
  cameraInlineAction: {
    alignItems: 'center',
    backgroundColor: '#F5F8FC',
    borderRadius: 9,
    flexDirection: 'row',
    gap: 5,
    minHeight: 32,
    paddingHorizontal: 9,
  },
  cameraInlineActionText: {
    color: '#00326D',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 10,
  },
  cameraInlineDangerAction: {
    backgroundColor: '#FFF1F0',
  },
  cameraInlineDangerActionText: {
    color: '#B42318',
  },
  occurrencesCameraName: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    marginTop: 1,
  },
  occurrencesState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 20,
    paddingHorizontal: 24,
    paddingVertical: 36,
  },
  occurrencesStateText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 10,
    textAlign: 'center',
  },
  occurrencesErrorText: {
    color: '#B42318',
  },
  occurrencesEmptyTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 17,
    marginTop: 12,
  },
  occurrencesList: {
    gap: 10,
    marginTop: 20,
  },
  occurrenceCard: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 14,
  },
  occurrenceCardPressed: {
    backgroundColor: '#F8FBFF',
    borderColor: '#B8D4E8',
  },
  occurrenceIcon: {
    alignItems: 'center',
    backgroundColor: '#FEF3F2',
    borderRadius: 12,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  occurrenceContent: {
    flex: 1,
    marginLeft: 12,
  },
  occurrenceTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 14,
  },
  occurrenceBody: {
    color: '#475467',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 3,
  },
  occurrenceDate: {
    color: '#98A2B3',
    fontFamily: WORKSPACE_DETAILS_FONTS.medium,
    fontSize: 10,
  },
  occurrenceFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 9,
  },
  occurrenceClipAction: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  occurrenceClipActionText: {
    color: '#00326D',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 11,
  },
  occurrenceClipUnavailable: {
    color: '#98A2B3',
    fontFamily: WORKSPACE_DETAILS_FONTS.medium,
    fontSize: 10,
  },
  occurrenceClipError: {
    color: '#B42318',
    fontFamily: WORKSPACE_DETAILS_FONTS.medium,
    fontSize: 12,
    textAlign: 'center',
  },
  occurrenceClipBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 24, 40, 0.72)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  occurrenceClipModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    padding: 16,
    width: '100%',
  },
  occurrenceClipHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  occurrenceClipEyebrow: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 10,
    letterSpacing: 1,
  },
  occurrenceClipTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 18,
    marginTop: 2,
  },
  occurrenceClipClose: {
    alignItems: 'center',
    backgroundColor: '#F2F4F7',
    borderRadius: 999,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  occurrenceClipVideo: {
    backgroundColor: '#000000',
    borderRadius: 12,
    height: 220,
  },
  cameraCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
  },
  cameraCardBody: {
    padding: 12,
  },
  cameraTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  cameraTitleWrap: {
    flex: 1,
    minWidth: 0,
  },
  cameraStatusBadge: {
    backgroundColor: '#F2F4F7',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  cameraStatusBadgeOnline: {
    backgroundColor: '#ECFDF3',
  },
  cameraStatusText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 11,
  },
  cameraStatusTextOnline: {
    color: '#027A48',
  },
  cameraProtocolText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    marginTop: 8,
  },
  cameraActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  cameraActionButton: {
    alignItems: 'center',
    backgroundColor: '#00326D',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 14,
  },
  cameraSecondaryButton: {
    alignItems: 'center',
    backgroundColor: '#F0F6FC',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 14,
  },
  cameraActionPrimaryText: {
    color: '#FFFFFF',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 12,
  },
  cameraActionSecondaryText: {
    color: '#00326D',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 12,
  },
  roomCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    width: '48%',
  },
  roomImage: {
    height: 128,
    width: '100%',
  },
  roomContent: {
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  roomName: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 14,
  },
  roomMeta: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    marginTop: 2,
  },
  emptyCameraState: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 74,
    padding: 14,
  },
  emptyCameraCopy: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  emptyCameraButton: {
    alignItems: 'center',
    backgroundColor: '#00326D',
    borderRadius: 12,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  snapshotImage: {
    borderRadius: 10,
    height: 100,
    width: '48%',
  },
  memberList: {
    gap: 10,
    marginBottom: 28,
    marginTop: 2,
  },
  memberRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 64,
    paddingHorizontal: 12,
  },
  person: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    marginBottom: 12,
    marginRight: 12,
    padding: 10,
    width: 92,
  },
  memberAvatarPlaceholder: {
    alignItems: 'center',
    backgroundColor: '#F0F6FC',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  memberInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
  },
  personName: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 13,
  },
  memberContact: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    marginTop: 1,
  },
  memberRole: {
    backgroundColor: '#F2F4F7',
    borderRadius: 999,
    color: '#475467',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 11,
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    textTransform: 'capitalize',
  },
  addPerson: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#9AA8BA',
    borderRadius: 25,
    borderStyle: 'dashed',
    borderWidth: 1,
    height: 50,
    justifyContent: 'center',
    marginBottom: 12,
    width: 82,
  },
  addPersonIcon: {
    fontSize: 20,
    lineHeight: 22,
  },
  addPersonText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
  },
  activityText: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.medium,
  },
  time: {
    color: '#777777',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
  },
  mutedText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  pressed: {
    opacity: 0.7,
  },
  errorText: {
    color: '#B42318',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  familyHeaderRow: {
    marginBottom: 4,
  },
  familySubtitle: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 12,
    marginTop: 3,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 24, 40, 0.45)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    width: '100%',
  },
  deleteCameraIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#FEE4E2',
    borderRadius: 999,
    height: 52,
    justifyContent: 'center',
    marginBottom: 12,
    width: 52,
  },
  keyboardModalWrap: {
    width: '100%',
  },
  modalTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 18,
  },
  modalSubtitle: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 6,
  },
  modalInput: {
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 14,
    borderWidth: 1,
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 14,
    marginTop: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  rolePicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  roleChip: {
    backgroundColor: '#F9FAFB',
    borderColor: '#D0D5DD',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  roleChipSelected: {
    backgroundColor: '#F0F6FC',
    borderColor: '#00326D',
  },
  roleChipText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 12,
  },
  roleChipTextSelected: {
    color: '#00326D',
  },
  inviteCodeBox: {
    backgroundColor: '#F0F6FC',
    borderColor: '#C9DDF2',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 14,
    padding: 12,
  },
  inviteCodeBoxPressed: {
    backgroundColor: '#E3EFFB',
  },
  inviteCodeHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inviteCodeLabel: {
    color: '#00326D',
    fontFamily: WORKSPACE_DETAILS_FONTS.semiBold,
    fontSize: 12,
  },
  inviteCodeText: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
  },
  modalActionButton: {
    alignItems: 'center',
    backgroundColor: '#00326D',
    borderRadius: 14,
    marginTop: 14,
    paddingVertical: 12,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  modalActionText: {
    color: '#FFFFFF',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 14,
  },
  modalDangerButton: {
    backgroundColor: '#FDECEA',
  },
  modalDangerText: {
    color: '#C0392B',
  },
  modalCancelButton: {
    alignItems: 'center',
    marginTop: 10,
    paddingVertical: 10,
  },
  modalCancelText: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.medium,
    fontSize: 14,
  },
  cameraLiveContent: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 40,
  },
  cameraLiveTopSpacer: {
    height: 2,
  },
  cameraLiveHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 14,
  },
  cameraLiveHeaderText: {
    flex: 1,
  },
  cameraLiveTitle: {
    color: '#101828',
    fontFamily: WORKSPACE_DETAILS_FONTS.bold,
    fontSize: 22,
  },
  cameraLiveSubtitle: {
    color: '#667085',
    fontFamily: WORKSPACE_DETAILS_FONTS.regular,
    fontSize: 13,
    marginTop: 2,
  },
  cameraLiveViewerCard: {
    aspectRatio: 16 / 9,
    backgroundColor: '#000000',
    borderRadius: 16,
    borderColor: '#D0D5DD',
    borderWidth: 1,
    overflow: 'hidden',
  },
  cameraLiveWebview: {
    flex: 1,
  },
  cameraLiveVideo: {
    flex: 1,
  },
});

export { styles };
