import { StyleSheet } from 'react-native';

const LIVE_VIEW_FONTS = {
  regular: 'Poppins-Regular',
  extraBold: 'Poppins-ExtraBold',
} as const;

export const styles = StyleSheet.create({
  content: {
    paddingHorizontal: 22,
    paddingBottom: 144,
  },
  topSpacer: {
    height: 34,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  backButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    alignItems: 'center',
  },
  headerBalance: {
    width: 32,
  },
  headerEyebrow: {
    color: '#019BDE',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 10,
    letterSpacing: 1.2,
    marginBottom: 3,
  },
  headerTitle: {
    color: '#111827',
    fontFamily: LIVE_VIEW_FONTS.extraBold,
    fontSize: 23,
    textAlign: 'center',
  },
  liveStatus: {
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
    marginBottom: 18,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#E9FBF4',
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#12B76A',
  },
  liveStatusText: {
    color: '#067647',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 12,
  },
  viewerCard: {
    aspectRatio: 16 / 9,
    overflow: 'hidden',
    borderRadius: 16,
    backgroundColor: '#000000',
    borderColor: '#D0D5DD',
    borderWidth: 1,
  },
  video: {
    width: '100%',
    height: '100%',
  },
  webview: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000',
  },
  historySection: {
    marginTop: 28,
    backgroundColor: '#FFFFFF',
    borderColor: '#E7EEF5',
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  historyHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  historyTitle: {
    color: '#101828',
    fontFamily: LIVE_VIEW_FONTS.extraBold,
    fontSize: 16,
  },
  historySubtitle: {
    color: '#667085',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 11,
    marginTop: 3,
  },
  historyCount: {
    alignItems: 'center',
    backgroundColor: '#E4F5FC',
    borderRadius: 999,
    height: 28,
    justifyContent: 'center',
    minWidth: 28,
    paddingHorizontal: 8,
  },
  historyCountText: {
    color: '#018AC7',
    fontFamily: LIVE_VIEW_FONTS.extraBold,
    fontSize: 12,
  },
  historyLoading: {
    paddingVertical: 16,
  },
  emptyHistory: {
    color: '#667085',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 12,
    lineHeight: 18,
    paddingVertical: 10,
  },
  historyItem: {
    alignItems: 'center',
    borderTopColor: '#EEF2F6',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 12,
  },
  historyItemPressed: {
    opacity: 0.68,
  },
  historyItemDisabled: {
    opacity: 0.58,
  },
  historyIcon: {
    alignItems: 'center',
    backgroundColor: '#FEF3F2',
    borderRadius: 10,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  historyText: {
    flex: 1,
  },
  historyItemTitle: {
    color: '#344054',
    fontFamily: LIVE_VIEW_FONTS.extraBold,
    fontSize: 12,
  },
  historyItemDate: {
    color: '#667085',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 11,
    marginTop: 2,
  },
  clipUnavailable: {
    color: '#98A2B3',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 10,
  },
  clipError: {
    color: '#B42318',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 11,
    lineHeight: 17,
    marginTop: 8,
  },
  clipModalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(16, 24, 40, 0.7)',
    flex: 1,
    justifyContent: 'center',
    padding: 20,
  },
  clipModalCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    padding: 16,
    width: '100%',
  },
  clipModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  clipModalEyebrow: {
    color: '#019BDE',
    fontFamily: LIVE_VIEW_FONTS.regular,
    fontSize: 10,
    letterSpacing: 1,
  },
  clipModalTitle: {
    color: '#101828',
    fontFamily: LIVE_VIEW_FONTS.extraBold,
    fontSize: 18,
    marginTop: 2,
  },
  clipCloseButton: {
    alignItems: 'center',
    backgroundColor: '#F2F4F7',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  clipVideo: {
    aspectRatio: 16 / 9,
    backgroundColor: '#000000',
    borderRadius: 12,
    overflow: 'hidden',
    width: '100%',
  },
});
