import { StyleSheet } from "react-native";

const INSIGHTS_COLORS = {
  gradientStart: "#03CDF4",
  gradientMiddle: "#019BDE",
  gradientEnd: "#01EBD0",
} as const;

const INSIGHTS_GRADIENT_COLORS = [
  INSIGHTS_COLORS.gradientStart,
  INSIGHTS_COLORS.gradientMiddle,
  INSIGHTS_COLORS.gradientEnd,
] as const;

const INSIGHTS_GRADIENT_LOCATIONS = [0.08, 0.38, 1] as const;

const INSIGHTS_FONTS = {
  manrope: "Manrope",
  regular: "Poppins-Regular",
  medium: "Poppins-Medium",
  bold: "Poppins-Bold",
  extraBold: "Poppins-ExtraBold",
  black: "Poppins-Black",
} as const;

const styles = StyleSheet.create({
  scrollContent: {
    alignItems: "center",
    paddingBottom: 132,
  },
  screen: {
    width: "100%",
    maxWidth: 390,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 36,
  },
  hero: {
    marginTop: 0,
  },
  modeButton: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  pressed: {
    opacity: 0.68,
  },
  titleLine: {
    alignItems: "flex-end",
    flexDirection: "row",
  },
  title: {
    height: 40,
    width: 142,
  },
  mode: {
    color: "#8D8D8D",
    fontFamily: INSIGHTS_FONTS.manrope,
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 28,
    marginLeft: 8,
  },
  subtitle: {
    color: "#404850",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    marginTop: 0,
  },
  cardLarge: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 32,
    minHeight: 425,
    paddingBottom: 28,
    paddingHorizontal: 24,
    paddingTop: 28,
    shadowColor: "#D7E4F0",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.72,
    shadowRadius: 28,
    elevation: 5,
  },
  incidentsHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 72,
  },
  cardTitle: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 29,
    lineHeight: 36,
  },
  cardSubtitle: {
    color: "#92A0B6",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 16,
  },
  periodArea: {
    alignItems: "flex-end",
    position: "relative",
  },
  periodButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    paddingLeft: 10,
    paddingVertical: 3,
  },
  periodText: {
    color: INSIGHTS_COLORS.gradientMiddle,
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 18,
  },
  periodMenu: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E7EEF5",
    borderRadius: 12,
    borderWidth: 1,
    minWidth: 122,
    padding: 6,
    position: "absolute",
    right: 0,
    shadowColor: "#A6B6C8",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
    top: 48,
    zIndex: 3,
  },
  periodMenuItem: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  periodMenuItemActive: {
    backgroundColor: "#E8F8FC",
  },
  periodMenuText: {
    color: "#404850",
    fontFamily: INSIGHTS_FONTS.extraBold,
    fontSize: 13,
    fontWeight: "800",
  },
  periodMenuTextActive: {
    color: INSIGHTS_COLORS.gradientMiddle,
  },
  chartContainer: {
    height: 192,
    marginTop: 118,
    width: "100%",
  },
  cardRooms: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 24,
    minHeight: 450,
    paddingHorizontal: 24,
    paddingTop: 30,
    shadowColor: "#D7E4F0",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.72,
    shadowRadius: 28,
    elevation: 5,
  },
  roomsTitle: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 36,
  },
  roomList: {
    gap: 23,
    marginTop: 28,
  },
  roomItem: {
    gap: 12,
  },
  roomTopLine: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  roomName: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 24,
  },
  roomValue: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    fontWeight: "900",
    lineHeight: 24,
  },
  roomTrack: {
    backgroundColor: "#E4E9EF",
    borderRadius: 999,
    height: 12,
    overflow: "hidden",
  },
  roomBar: {
    borderRadius: 999,
    height: "100%",
  },
  roomBarQuarto: {
    backgroundColor: INSIGHTS_COLORS.gradientEnd,
    width: "85%",
  },
  roomBarSala: {
    backgroundColor: INSIGHTS_COLORS.gradientStart,
    width: "50%",
  },
  roomBarCozinha: {
    backgroundColor: INSIGHTS_COLORS.gradientMiddle,
    width: "18%",
  },
  roomBarBanheiro: {
    backgroundColor: INSIGHTS_COLORS.gradientMiddle,
    width: "10%",
  },
  dailyCard: {
    alignItems: "center",
    backgroundColor: "#F0F4F8",
    borderRadius: 12,
    marginTop: 24,
    minHeight: 400,
    paddingHorizontal: 24,
    paddingTop: 62,
  },
  dailyBadge: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    height: 64,
    justifyContent: "center",
    shadowColor: "#A6B6C8",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    width: 64,
    elevation: 3,
  },
  dailyLabel: {
    color: "#667085",
    fontFamily: INSIGHTS_FONTS.black,
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 2,
    lineHeight: 18,
    marginTop: 24,
  },
  dailyValue: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 62,
    lineHeight: 72,
    marginTop: 14,
  },
  dailyText: {
    color: "#404850",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 27,
    marginTop: 18,
    textAlign: "center",
  },
  activityTitle: {
    height: 52,
    marginLeft: 8,
    marginTop: 46,
    width: 190,
  },
  activityCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 24,
    minHeight: 320,
    paddingHorizontal: 40,
    paddingTop: 26,
    shadowColor: "#D7E4F0",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.72,
    shadowRadius: 28,
    elevation: 5,
  },
  cameraTitle: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 28,
    lineHeight: 36,
  },
  cameraSubtitle: {
    color: "#9A9A9A",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 20,
  },
  activityChart: {
    height: 96,
    marginTop: 22,
    position: "relative",
  },
  activityTrack: {
    backgroundColor: "#E4E9EF",
    borderRadius: 999,
    height: 14,
    overflow: "hidden",
    position: "relative",
    zIndex: 2,
  },
  activitySegment: {
    backgroundColor: INSIGHTS_COLORS.gradientStart,
    height: 14,
    position: "absolute",
    top: 0,
  },
  activitySegmentFirst: {
    left: 0,
    width: "18%",
  },
  activitySegmentSecond: {
    left: "23%",
    width: "7%",
  },
  activitySegmentThird: {
    left: "33%",
    width: "53%",
  },
  activityGrid: {
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  activityTick: {
    alignItems: "center",
    justifyContent: "flex-end",
  },
  activityDash: {
    borderColor: "#D9D9D9",
    borderLeftWidth: 1,
    borderStyle: "dashed",
    flex: 1,
    marginBottom: 8,
    marginTop: 8,
  },
  activityTime: {
    color: "#8D8D8D",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
  },
  legend: {
    gap: 20,
    marginTop: 22,
  },
  legendRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  legendActiveDot: {
    backgroundColor: INSIGHTS_COLORS.gradientStart,
    borderRadius: 8,
    height: 16,
    marginRight: 16,
    width: 16,
  },
  legendInactiveDot: {
    backgroundColor: "#E4E9EF",
    borderRadius: 8,
    height: 16,
    marginRight: 16,
    width: 16,
  },
  legendText: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    fontWeight: "500",
    lineHeight: 24,
  },
  exportButton: {
    alignItems: "center",
    borderRadius: 12,
    marginTop: 24,
    minHeight: 96,
    overflow: "hidden",
  },
  exportGradient: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 28,
    justifyContent: "center",
    minHeight: 96,
    paddingHorizontal: 28,
  },
  exportText: {
    color: "#FFFFFF",
    fontFamily: INSIGHTS_FONTS.black,
    fontSize: 21,
    fontWeight: "900",
    lineHeight: 32,
    textAlign: "center",
  },
});

export {
  INSIGHTS_COLORS,
  INSIGHTS_FONTS,
  INSIGHTS_GRADIENT_COLORS,
  INSIGHTS_GRADIENT_LOCATIONS,
  styles,
};
