import { StyleSheet } from "react-native";

const INSIGHTS_COLORS = {
  gradientStart: "#03CDF4",
  gradientMiddle: "#019BDE",
  gradientEnd: "#01EBD0",
} as const;

const INSIGHTS_GRADIENT_COLORS = [
  INSIGHTS_COLORS.gradientStart,
  INSIGHTS_COLORS.gradientMiddle,
  INSIGHTS_COLORS.gradientEnd,
] as const;

const INSIGHTS_GRADIENT_LOCATIONS = [0.08, 0.38, 1] as const;

const INSIGHTS_FONTS = {
  manrope: "Manrope",
  regular: "Poppins-Regular",
  medium: "Poppins-Medium",
  bold: "Poppins-Bold",
  extraBold: "Poppins-ExtraBold",
  black: "Poppins-Black",
} as const;

const styles = StyleSheet.create({
  page: {
    flex: 1,
  },
  scrollContent: {
    alignItems: "center",
  },
  screen: {
    width: "100%",
    maxWidth: 390,
    paddingBottom: 36,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  hero: {
    marginTop: 0,
    position: "relative",
  },
  heroTopRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    zIndex: 2,
  },
  heroDismissLayer: {
    bottom: -520,
    left: -24,
    position: "absolute",
    right: -24,
    top: 0,
    zIndex: 1,
  },
  pressed: {
    opacity: 0.68,
  },
  title: {
    flexShrink: 1,
    height: 42,
    width: 136,
  },
  heroWorkspaceArea: {
    flex: 1,
    position: "relative",
  },
  heroChip: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: INSIGHTS_COLORS.gradientMiddle,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    minWidth: 0,
    gap: 4,
    minHeight: 34,
    maxWidth: "75%",
    paddingHorizontal: 10,
  },
  heroChipText: {
    flex: 1,
    flexShrink: 1,
    color: INSIGHTS_COLORS.gradientMiddle,
    fontFamily: INSIGHTS_FONTS.manrope,
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 18,
  },
  workspaceMenu: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D8E6F1",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 8,
    minWidth: 230,
    padding: 8,
    position: "absolute",
    right: 0,
    shadowColor: "#B3C4D5",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    top: 34,
    zIndex: 4,
    elevation: 6,
  },
  workspaceMenuItem: {
    alignItems: "center",
    borderRadius: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 38,
    paddingHorizontal: 10,
  },
  workspaceMenuItemSelected: {
    backgroundColor: "#EDF9FD",
  },
  workspaceMenuItemText: {
    color: "#404850",
    flex: 1,
    flexShrink: 1,
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 13,
    lineHeight: 18,
    paddingRight: 8,
  },
  workspaceMenuItemTextSelected: {
    color: INSIGHTS_COLORS.gradientMiddle,
  },
  subtitle: {
    color: "#404850",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 0,
  },
  filterButton: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#000000",
    borderRadius: 32,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  filterButtonText: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 12,
    lineHeight: 22,
  },
  cardLarge: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 24,
    paddingBottom: 28,
    paddingHorizontal: 24,
    paddingTop: 28,
    shadowColor: "#D7E4F0",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.72,
    shadowRadius: 28,
    elevation: 5,
  },
  incidentsHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  cardTitle: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 25,
    lineHeight: 32,
  },
  cardSubtitle: {
    color: "#92A0B6",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 12,
    lineHeight: 14,
    marginTop: 2,
  },
  incidentsControls: {
    alignItems: "flex-end",
    marginLeft: 12,
  },
  activeFiltersSummary: {
    alignItems: "flex-end",
    gap: 4,
    marginTop: 10,
  },
  activeFilterText: {
    color: INSIGHTS_COLORS.gradientMiddle,
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  chartContainer: {
    height: 192,
    marginTop: 38,
    width: "100%",
  },
  cardRooms: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 24,
    paddingHorizontal: 24,
    paddingVertical: 30,
    shadowColor: "#D7E4F0",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.72,
    shadowRadius: 28,
    elevation: 5,
  },
  roomsTitle: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 25,
    lineHeight: 36,
  },
  roomList: {
    gap: 23,
    marginTop: 28,
  },
  roomItem: {
    gap: 12,
  },
  roomTopLine: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  roomName: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    lineHeight: 24,
  },
  roomValue: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    lineHeight: 24,
  },
  roomTrack: {
    backgroundColor: "#E4E9EF",
    borderRadius: 999,
    height: 12,
    overflow: "hidden",
  },
  roomBar: {
    borderRadius: 999,
    height: "100%",
  },
  roomBarQuarto: {
    backgroundColor: INSIGHTS_COLORS.gradientEnd,
    width: "85%",
  },
  roomBarSala: {
    backgroundColor: INSIGHTS_COLORS.gradientStart,
    width: "50%",
  },
  roomBarCozinha: {
    backgroundColor: INSIGHTS_COLORS.gradientMiddle,
    width: "18%",
  },
  roomBarBanheiro: {
    backgroundColor: INSIGHTS_COLORS.gradientMiddle,
    width: "10%",
  },
  dailyCard: {
    alignItems: "center",
    backgroundColor: "#F6FAFE",
    borderColor: INSIGHTS_GRADIENT_COLORS[1],
    borderWidth: 1,
    borderRadius: 12,
    marginTop: 24,
    minHeight: 400,
    paddingHorizontal: 24,
    paddingTop: 62,
  },
  dailyBadge: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 32,
    elevation: 3,
    height: 64,
    justifyContent: "center",
    shadowColor: "#A6B6C8",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
    width: 64,
  },
  dailyLabel: {
    color: "#667085",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 13,
    letterSpacing: 2,
    lineHeight: 18,
    marginTop: 24,
  },
  dailyValue: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 62,
    lineHeight: 72,
    marginTop: 14,
  },
  dailyText: {
    color: "#404850",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    lineHeight: 24,
    marginHorizontal: 20,
    marginTop: 18,
    textAlign: "center",
  },
  activityTitle: {
    height: 52,
    marginLeft: 8,
    marginTop: 46,
    width: 190,
  },
  activityCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    marginTop: 24,

    paddingHorizontal: 40,
    paddingVertical: 26,
    shadowColor: "#D7E4F0",
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.72,
    shadowRadius: 28,
    elevation: 5,
  },
  cameraTitle: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 28,
    lineHeight: 36,
  },
  cameraSubtitle: {
    color: "#9A9A9A",
    fontFamily: INSIGHTS_FONTS.regular,
    fontSize: 16,
    lineHeight: 20,
  },
  activityChart: {
    height: 96,
    marginTop: 22,
    position: "relative",
  },
  activityTrack: {
    backgroundColor: "#E4E9EF",
    borderRadius: 999,
    height: 14,
    overflow: "hidden",
    position: "relative",
    zIndex: 2,
  },
  activitySegment: {
    backgroundColor: INSIGHTS_COLORS.gradientStart,
    height: 14,
    position: "absolute",
    top: 0,
  },
  activitySegmentFirst: {
    left: 0,
    width: "18%",
  },
  activitySegmentSecond: {
    left: "23%",
    width: "7%",
  },
  activitySegmentThird: {
    left: "33%",
    width: "53%",
  },
  activityGrid: {
    bottom: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  activityTick: {
    alignItems: "center",
    justifyContent: "flex-end",
  },
  activityDash: {
    borderColor: "#D9D9D9",
    borderLeftWidth: 1,
    borderStyle: "dashed",
    flex: 1,
    marginBottom: 8,
    marginTop: 8,
  },
  activityTime: {
    color: "#8D8D8D",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 12,
    fontWeight: "500",
    lineHeight: 16,
  },
  legend: {
    gap: 20,
    marginTop: 22,
  },
  legendRow: {
    alignItems: "center",
    flexDirection: "row",
  },
  legendActiveDot: {
    backgroundColor: INSIGHTS_COLORS.gradientStart,
    borderRadius: 8,
    height: 16,
    marginRight: 16,
    width: 16,
  },
  legendInactiveDot: {
    backgroundColor: "#E4E9EF",
    borderRadius: 8,
    height: 16,
    marginRight: 16,
    width: 16,
  },
  legendText: {
    color: "#171C1F",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    lineHeight: 24,
  },
  exportButton: {
    alignItems: "center",
    borderRadius: 12,
    marginTop: 24,
    minHeight: 96,
    overflow: "hidden",
  },
  exportGradient: {
    alignItems: "center",
    borderRadius: 12,
    flex: 1,
    flexDirection: "row",
    gap: 28,
    justifyContent: "center",
    minHeight: 96,
    width: "100%",
  },
  exportText: {
    color: "#FFFFFF",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 18,
    lineHeight: 32,
    textAlign: "center",
  },
  bottomSheetRoot: {
    flex: 1,
    justifyContent: "flex-end",
  },
  bottomSheetBackdropPressable: {
    ...StyleSheet.absoluteFillObject,
  },
  bottomSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#000000",
  },
  bottomSheetContainer: {
    backgroundColor: "#F6FAFE",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingBottom: 36,
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  bottomSheetHandle: {
    alignSelf: "center",
    backgroundColor: "#CAD4DE",
    borderRadius: 999,
    height: 5,
    marginBottom: 20,
    width: 52,
  },
  bottomSheetTitle: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 24,
    lineHeight: 30,
  },
  bottomSheetSectionTitle: {
    color: "#404850",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 16,
    lineHeight: 22,
    marginTop: 22,
  },
  bottomSheetOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 12,
  },
  filterOptionGradientBorder: {
    borderRadius: 20,
    padding: 1,
    width: "45%",
  },
  filterOptionCard: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#000000",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    minHeight: 40,
    paddingHorizontal: 14,
    width: "45%",
  },
  filterOptionCardSelected: {
    borderColor: "#FFFFFF",
    borderWidth: 0,
  },
  filterOptionCardGradient: {
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#000000",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 7,
    minHeight: 40,
    paddingHorizontal: 14,
    width: "100%",
  },
  filterOptionCardGradientSelected: {
    borderColor: "#FFFFFF",
    borderWidth: 0,
    width: "100%",
  },
  filterOptionText: {
    color: "#000000",
    fontFamily: INSIGHTS_FONTS.medium,
    fontSize: 13,
    lineHeight: 20,
  },
  filterOptionTextActive: {
    color: INSIGHTS_COLORS.gradientMiddle,
  },
  filterApplyButton: {
    alignItems: "center",
    backgroundColor: "#000000",
    borderRadius: 12,
    justifyContent: "center",
    marginTop: 28,
    minHeight: 54,
  },
  filterApplyButtonText: {
    color: "#FFFFFF",
    fontFamily: INSIGHTS_FONTS.bold,
    fontSize: 16,
    lineHeight: 22,
  },
});

export {
  INSIGHTS_COLORS,
  INSIGHTS_FONTS,
  INSIGHTS_GRADIENT_COLORS,
  INSIGHTS_GRADIENT_LOCATIONS,
  styles,
};
